{% set name = "kwimage" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kwimage-{{ version }}.tar.gz
  sha256: 329a36fa5883c0dc85b2b777621d372cc24f738eec961df45c78ec187ca1f010

build:
  noarch: python
  entry_points:
    - kwimage = kwimage.cli.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=41.0.1
    - wheel >=0.37.1
  run:
    - affine >=2.3.0
    - distinctipy >=1.2.1
    - kwarray >=0.6.19
    - networkx >=2.7
    - numpy
    - parse >=1.14.0
    - pillow
    - py-opencv
    - python >=3.8
    - scikit-image >=0.17.0
    - scipy
    - scriptconfig
    - shapely
    - ubelt >=1.3.3

test:
  imports:
    - kwimage
  commands:
    - pip check
    - kwimage --help
  requires:
    - pip

about:
  home: https://gitlab.kitware.com/computer-vision/kwimage
  summary: The kwimage module
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Erotemic
    - vicentebolea
